### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by istian** [danicomas/angular-jquery-validate#1]
Hi,

I'm having an issue in angular-jquery-validate.js @line: 30.

Using dev console, the "elem" variable is my form element but there was no "validate()" is attached to it.

scope.$watch('formvalidatorconfig', function (value) {
                debugger;
                if (value) {
                    elem.validate(value);
                    if (value.validateOnInit)
                        scope.formvalidatorapi.validate();
}});

Could someone please give an insight?

Thanks

**Comment by istian** [comment]
it seems that I have to wrap "elem" to jquery => $(elem) to make it work.

**Comment by danicomas** [comment]
elem should work without $(elem). It is possible that you have registered script libraries in wrong order or you don't use the last angularjs.

**Comment by istian** [comment]
Hi @danicomas,

You're correct. I'm new to angularjs and I actually put jquery after angularjs and that is why. Thanks for your reply though.
