### ISSUE TITLE
ui.bootstrap Modal 

### ISSUE THREAD

**Issue by openainext** [danicomas/angular-jquery-validate#3]
$scope.eventformvalidateapi  null

**Comment by danicomas** [comment]
Attach your example, here or a jsFiddle thanks

**Comment by openainext** [comment]
Find the problem  3q

**Comment by danicomas** [comment]
Can you close this issue If the problem is solved? Thanks!

**Comment by saniokazzz** [comment]
@wanglong167 how have you solved the issue?
